version: '3.8'

services:
  api:
    image: jonathanleedev/sparrow-express-api:latest
    ports:
      - '8080:8080'
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DATABASE_URI: ${DATABASE_URI}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
